### ISSUE TITLE
MPI Array error in PdfGeneratorWithSelectionFunction

### ISSUE THREAD

**Issue by josephwkania** [radiocosmology/caput#209]
I've encountered this error while running the ringmap stack. 
```
525.9s [MPI  0/32] - INFO     draco.synthesis.mockcatalog.PdfGeneratorWithSelectionFunction: Starting next for task PdfGeneratorWithSelectionFunction
Traceback (most recent call last):
  File "~/code/rolling/caput/caput/scripts/runner.py", line 586, in <module>
    cli()
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/code/rolling/caput/caput/scripts/runner.py", line 161, in run
    P.run()
  File "~/code/rolling/caput/caput/pipeline.py", line 633, in run
    out = task._pipeline_next()
  File "~/code/rolling/caput/caput/pipeline.py", line 1085, in _pipeline_next
    out = self.next(*args)
  File "~/code/rolling/draco/draco/core/task.py", line 370, in next
    output = self.process(*input)
  File "~/code/rolling/draco/draco/synthesis/mockcatalog.py", line 472, in process
    z_weights_sum = self.comm.allreduce(z_weights.sum())
  File "mpi4py/MPI/Comm.pyx", line 1289, in mpi4py.MPI.Comm.allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1216, in mpi4py.MPI.PyMPI_allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1168, in mpi4py.MPI.PyMPI_allreduce_intra
  File "mpi4py/MPI/msgpickle.pxi", line 1033, in mpi4py.MPI.PyMPI_reduce_p2p
  File "mpi4py/MPI/Op.pyx", line 33, in mpi4py.MPI.Op.__call__
  File "mpi4py/MPI/opimpl.pxi", line 19, in mpi4py.MPI._op_SUM
  File "~/code/rolling/caput/caput/mpiarray.py", line 1634, in __array_ufunc__
    args, dist_axis = _mpi_to_ndarray(inputs)
  File "~/code/rolling/caput/caput/mpiarray.py", line 1860, in _mpi_to_ndarray
    raise AxisException(
caput.mpiarray.AxisException: An input to a ufunc has an MPIArray, which is missing its axis property.If using a lower-case MPI.Comm function, please use its upper-case alternative.Pickling does not preserve the axis property.Otherwise, please file an issue on caput with a stacktrace.
```

**Comment by josephwkania** [comment]
Fixed with updates to MPIArray and [pull #189 in Draco](https://github.com/radiocosmology/draco/pull/189).
