### ISSUE TITLE
h5py error: "TypeError: 'compression' is an invalid keyword argument for this function"

### ISSUE THREAD

**Issue by dstndstn** [radiocosmology/caput#226]
Hi,

I'm trying to run a CHIME baseband pipeline on a new system, and am hitting the following bug.  Googling the error message reveals a closed issue against h5py, suggesting that the "compression" argument should not be passed to the h5py File constructor, at least for h5py >= 2.7.0 (we have h5py = 3.7.0); "compression" should instead be passed at dataset creation time.

Ironically, in this case it appears to be passing None for the compression kwargs...
```
kwargs= {'compression': None, 'compression_opts': None}
```

```
INFO:caput.pipeline:WriteSingleFile writing data to file /gpfs/dlang/chimefrb-offline-beamformer/baseband/processed/2021/11/05/astro_195718715/meta_products/beamform_195718715.h5.
Traceback (most recent call last):
  File "/home/dlang/.local/bin/caput-pipeline", line 8, in <module>
    sys.exit(cli())
  File "/home/dlang/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dlang/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dlang/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dlang/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dlang/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/scripts/runner.py", line 161, in run
    P.run()
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/pipeline.py", line 637, in run
    out = task._pipeline_next()
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/pipeline.py", line 1089, in _pipeline_next
    out = self.next(*args)
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/pipeline.py", line 1363, in next
    return self.read_process_write(input, self.input_filename, self.output_filename)
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/pipeline.py", line 1273, in read_process_write
    self.write_output(
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/pipeline.py", line 1630, in write_output
    output.save(filename, file_format=file_format, **kwargs)
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/memh5.py", line 2017, in save
    self._data.to_file(
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/memh5.py", line 628, in to_file
    with file_format.open(filename, mode, **kwargs) as f:
  File "/home/dlang/.local/lib/python3.9/site-packages/caput/fileformats.py", line 84, in open
    return h5py.File(*args, **kwargs)
  File "/home/dlang/.local/lib/python3.9/site-packages/h5py/_hl/files.py", line 525, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
  File "/home/dlang/.local/lib/python3.9/site-packages/h5py/_hl/files.py", line 164, in make_fapl
    raise TypeError(msg)
### TypeError: 'compression' is an invalid keyword argument for this function
```

H5py issue mentioning this:  (https://github.com/h5py/h5py/issues/1261)

**Comment by jrs65** [comment]
We don't really use that pipeline functionality in CHIME (i.e. the `_OneAndOne` base class) and so we haven't noticed a failure.

I suspect the thing to do is to remove the compression arguments that are being passed by that class. They won't actually work properly anyway. To add compression parameters you need to attach them to the MemDataset's and then they get pulled out of there when the data is written out.

**Comment by jrs65** [comment]
You can see how we do it in the draco pipeline base task here: https://github.com/radiocosmology/draco/blob/master/draco/core/task.py#L444

**Comment by dstndstn** [comment]
The CHIME/FRB baseband-analysis pipeline does use that functionality.

I did this hack and it at least allowed the code to proceed (without compression, obvsly)

```
--- caput/caput/fileformats.py  2022-10-13 15:51:10.718115466 -0400
+++ /home/dlang/.local/lib/python3.9/site-packages/caput/fileformats.py 2022-10-13 15:49:30.551617000 -0400
@@ -81,6 +81,10 @@
     @staticmethod
     def open(*args, **kwargs):
         """Open an HDF5 file using h5py."""
+        print('Opening an h5py file with args=', args, 'and kwargs=', kwargs)
+        # H5py versions >= 2.7.0 can't handle compression= passed as an arg to File().
+        comp = kwargs.pop('compression', None)
+        compargs = kwargs.pop('compression_opts', None)
         return h5py.File(*args, **kwargs)
```

**Comment by jrs65** [comment]
@dstndstn if you can send in a PR that would be great. As you say it's not the ideal fix, but at least things aren't exploding any more.

**Comment by kaitshin** [comment]
@dstndstn did a PR ever get open/merged in for this? We've been testing getting the baseband pipeline at CANFAR to work and now seem to be running into this issue too.  I'm also happy to open a PR with Dustin's code above if that seems to be the right  move.

**Comment by jrs65** [comment]
@kaitshin @leungcalvin can you try testing #233 as an alternative fix?
