### ISSUE TITLE
mpi4py 2.0 compatibility

### ISSUE THREAD

**Issue by kiyo-masui** [radiocosmology/caput#23]
Looks like `mpiarray` is not compatible with mpi4py 2.0, which was recently released.  Error in unit tests below:

    ERROR: test_create_dataset (caput.tests.test_memh5_parallel.TestMemGroupDistributed)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/radiocosmology/caput/caput/tests/test_memh5_parallel.py", line 25, in test_create_dataset
        d_array_T = d_array.redistribute(axis=1)
      File "/home/travis/build/radiocosmology/caput/caput/mpiarray.py", line 402, in redistribute
        mpiutil.typemap(self.dtype)
      File "/home/travis/build/radiocosmology/caput/caput/mpiutil.py", line 163, in typemap
        return MPI.__TypeDict__[np.dtype(dtype).char]
    AttributeError: 'module' object has no attribute '__TypeDict__'

**Comment by jrs65** [comment]
Okay. That's what you get when you use private interfaces I guess. I'll take a look, I'm trying to port `scalapy` to mpi4py 2.0 as well, so it'll probably effect both.

**Comment by kiyo-masui** [comment]
Is this fixed?

**Comment by jrs65** [comment]
Yes. No idea why I didn't close it though. Fixed in b2726522
