### ISSUE TITLE
Properly handle numpy Unicode in memh5

### ISSUE THREAD

**Issue by ljgray** [radiocosmology/caput#230]
`dtype('<U32')` is a numpy Unicode type, which is [explicitly not supported](https://docs.h5py.org/en/stable/strings.html#what-about-numpy-s-u-type) by h5py. ~~The following error occurs occasionally when saving a distributed dataset as a result of this. We need to figure out why this only happens occasionally (it has happened 4 times out of over 300 rev_06 daily pipeline runs).~~

```
  2590.0s [MPI   0/144] - INFO     draco.analysis.transform.CollateProducts: Starting next for task CollateProducts
  2590.4s [MPI   0/144] - INFO     draco.analysis.transform.CollateProducts: Distributing across 'freq' axis
  2592.7s [MPI 115/144] - WARNING  py.warnings: /project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/mpiarray.py:1760: RuntimeWarning: overflow encountered in multiply
  super().__array_ufunc__(ufunc, method, *_mpi_to_ndarray(inputs), **kwargs)

  2594.2s [MPI   0/144] - DEBUG    draco.analysis.transform.CollateProducts: NaN found. Dumping nandump_CollateProducts_file016.h5
  2594.2s [MPI   0/144] - DEBUG    h5py._conv: Creating converter from 5 to 3
Traceback (most recent call last):
  File "/project/6003614/chime/chime_env/modules/chime/pipeline/2022.09/code/caput/caput/scripts/runner.py", line 586, in <module>
    cli()
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2022.06/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2022.06/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2022.06/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2022.06/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2022.06/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/project/6003614/chime/chime_env/modules/chime/pipeline/2022.09/code/caput/caput/scripts/runner.py", line 161, in run
    P.run()
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/pipeline.py", line 637, in run
    out = task._pipeline_next()
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/pipeline.py", line 1089, in _pipeline_next
    out = self.next(*args)
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/draco/draco/core/task.py", line 379, in next
    output = self._process_output(output)
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/draco/draco/core/task.py", line 433, in _process_output
    output = self._nan_process_output(output)
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/draco/draco/core/task.py", line 526, in _nan_process_output
    self.write_output(outfile, output)
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/pipeline.py", line 1630, in write_output
    output.save(filename, file_format=file_format, **kwargs)
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/memh5.py", line 2017, in save
    self._data.to_file(
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/memh5.py", line 637, in to_file
    _distributed_group_to_file(
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/memh5.py", line 2669, in _distributed_group_to_file
    distributed_dataset_names = deep_group_copy(
  File "/project/6003614/chime/chime_processed/daily/rev_06/code/caput/caput/memh5.py", line 2598, in deep_group_copy
    g2.create_dataset(
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc10/openmpi4/hdf5-mpi/1.12.1/lib/python3.10/site-packages/h5py-3.6.0-py3.10-linux-x86_64.egg/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc10/openmpi4/hdf5-mpi/1.12.1/lib/python3.10/site-packages/h5py-3.6.0-py3.10-linux-x86_64.egg/h5py/_hl/dataset.py", line 91, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1753, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U32')
```

**Comment by jrs65** [comment]
This shouldn't happen if `convert_dataset_strings` is set in the `._to_file(...)` call.

**Comment by jrs65** [comment]
Though I'm a bit surprised that this only happens occasionally and not every time.

**Comment by ljgray** [comment]
I think that it may be related to nan dumps

**Comment by ljgray** [comment]
I updated the traceback to what occurs in the daily pipeline. The same error occurred while trying to save a timestream after the SiderealGrouper stage (meaning it passed the nan check in CollateProducts), but other days were fine with saving timestreams. Also, these were days that ran fine in the rev_06 pipeline, So whatever is causing this doesn't seem to be overly consistent

**Comment by ljgray** [comment]
This is due to distributed datasets not being converted from unicode types. It could be useful to at least check if distributed datasets are of unicode type, even if they don't get converted automatically

**Comment by ljgray** [comment]
I'm closing this as the original issue is not due to memh5 and memh5 is behaving as intended.
