### ISSUE TITLE
Attribute Error on installation

### ISSUE THREAD

**Issue by anguta** [radiocosmology/caput#52]
I'm trying to install caput within a conda environment on a macbook and I'm getting the following errors. I have installed all of the dependencies listed in requirements.txt 

(hirax) LMC-065168:caput ewallwic$ python setup.py install
setup.py:36: UserWarning: Could not install additional Skyfield data.
  warnings.warn("Could not install additional Skyfield data.")
running install
running bdist_egg
running egg_info
writing requirements to caput.egg-info/requires.txt
writing caput.egg-info/PKG-INFO
writing top-level names to caput.egg-info/top_level.txt
writing dependency_links to caput.egg-info/dependency_links.txt
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    url="http://github.com/radiocosmology/caput"
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
    sdist.add_defaults(self)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
    self._add_defaults_python()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/sdist.py", line 134, in _add_defaults_python
    for _, src_dir, _, filenames in build_py.data_files:
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/build_py.py", line 66, in __getattr__
    self.data_files = self._get_data_files()
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/build_py.py", line 83, in _get_data_files
    return list(map(self._get_pkg_data_files, self.packages or ()))
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/build_py.py", line 95, in _get_pkg_data_files
    for file in self.find_data_files(package, src_dir)
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/build_py.py", line 104, in find_data_files
    src_dir,
  File "/Users/ewallwic/miniconda2/envs/hirax/lib/python2.7/site-packages/setuptools/command/build_py.py", line 228, in _get_platform_patterns
    spec.get('', []),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kiyo-masui** [comment]
Please try the branch for #53 and let me know if it fixes your issue.
