### ISSUE TITLE
Issues with latest version of master includes pull request #66

### ISSUE THREAD

**Issue by cahofer** [radiocosmology/caput#67]
I pulled the latest version of master and ran into this issue when trying to save a file.

This is the config file I was running (wanted to save a simulated time stream file) 

`
pipeline:

    tasks:

      - type: draco.core.task.SetMPILogging
        params:
            level_all: DEBUG
            level_rank0: DEBUG

      - type: draco.core.io.LoadProductManager
        out: manager
        params:
            product_directory: /project/rpp-krs/chime/beam_transfers/pb_band0/

      - type: draco.core.io.LoadFilesFromParams
        out: sstream
        params:
            files: "/scratch/cahofer/pass1_p/simulations/freqband_700-800/timingerrors/0ps/siderealstream_band0_newgroup_0.h5"

      - type: draco.synthesis.stream.ExpandProducts
        requires: manager
        in: sstream
        out: sstream_exp

      - type: draco.synthesis.stream.MakeTimeStream
        requires: [sstream_exp, manager]
        out: tstream
        params:
            start_time: 2015-06-21T13:45:00Z
            end_time: 2015-06-22T14:15:00Z
            integration_time: 60
            save: True
            output_root: "tstream_test"
`

This is the traceback (sorry this is a bit overkill was running 4 processes)

`
    57.5s [MPI 0/4] - INFO     draco.core.task.MakeTimeStream: Starting next for task MakeTimeStream
Traceback (most recent call last):
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 171, in <module>
Traceback (most recent call last):
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 171, in <module>
Traceback (most recent call last):
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 171, in <module>
Traceback (most recent call last):
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 171, in <module>
    dispatch_commands([run, queue])
    dispatch_commands([run, queue])
    dispatch_commands([run, queue])
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch_commands([run, queue])
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    dispatch(parser, *args, **kwargs)
    dispatch(parser, *args, **kwargs)
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    dispatch(parser, *args, **kwargs)
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in lines:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in lines:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
    for line in result:
    for line in result:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    for line in result:
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 24, in run
    result = function(*positional, **keywords)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 24, in run
    result = function(*positional, **keywords)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 24, in run
    result = function(*positional, **keywords)
    P.run()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/scripts/caput-pipeline", line 24, in run
    P.run()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 472, in run
    P.run()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 472, in run
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 472, in run
    P.run()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 472, in run
    out = task._pipeline_next()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 817, in _pipeline_next
    out = task._pipeline_next()
    out = task._pipeline_next()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 817, in _pipeline_next
    out = task._pipeline_next()
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 817, in _pipeline_next
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 817, in _pipeline_next
    out = self.next(*args)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 316, in next
    out = self.next(*args)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 316, in next
    out = self.next(*args)
    out = self.next(*args)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 316, in next
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 316, in next
    self._save_output(output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 360, in _save_output
    self._save_output(output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 360, in _save_output
    self._save_output(output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 360, in _save_output
    self._save_output(output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/task.py", line 360, in _save_output
    self.write_output(outfile, output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 1267, in write_output
    self.write_output(outfile, output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 1267, in write_output
    self.write_output(outfile, output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 1267, in write_output
    self.write_output(outfile, output)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/pipeline.py", line 1267, in write_output
    output.save(filename)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1467, in save
    output.save(filename)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1467, in save
    output.save(filename)
    output.save(filename)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1467, in save
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1467, in save
    self._data.to_hdf5(filename, **kwargs)
    self._data.to_hdf5(filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 487, in to_hdf5
    self._data.to_hdf5(filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 487, in to_hdf5
    self._data.to_hdf5(filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 487, in to_hdf5
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 487, in to_hdf5
    _distributed_group_to_hdf5_parallel(self, filename, **kwargs)
    _distributed_group_to_hdf5_parallel(self, filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1952, in _distributed_group_to_hdf5_parallel
    _distributed_group_to_hdf5_parallel(self, filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1952, in _distributed_group_to_hdf5_parallel
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1952, in _distributed_group_to_hdf5_parallel
    _distributed_group_to_hdf5_parallel(self, filename, **kwargs)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1952, in _distributed_group_to_hdf5_parallel
    _copy_to_file(group, f)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1924, in _copy_to_file
    _copy_to_file(group, f)
    _copy_to_file(group, f)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1924, in _copy_to_file
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1924, in _copy_to_file
    _copy_to_file(group, f)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/memh5.py", line 1924, in _copy_to_file
    item.data.to_hdf5(h5group, key)
    item.data.to_hdf5(h5group, key)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/mpiarray.py", line 563, in to_hdf5
    item.data.to_hdf5(h5group, key)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/mpiarray.py", line 563, in to_hdf5
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/mpiarray.py", line 563, in to_hdf5
    item.data.to_hdf5(h5group, key)
  File "/project/6003614/cahofer/ch_pipeline/venv/src/caput/caput/mpiarray.py", line 563, in to_hdf5
    dset[sl] = self[:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    dset[sl] = self[:]
    dset[sl] = self[:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    dset[sl] = self[:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/project/6003614/chime/chime_env/2018_04/base/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
IOError: Can't prepare for writing data (MPI_ERR_COUNT: invalid count argument)

`

When I revert to commit `fc7566f` on master things are working fine again.

**Comment by cahofer** [comment]
I am closing this because I think this was related to some weirdness with the chime_env... sorry about that
