### ISSUE TITLE
Error installing caput on top of 2019_01_py3/stable_base.sh

### ISSUE THREAD

**Issue by fandinomat** [radiocosmology/caput#91]
To reproduce, do on cedar:

  source /project/rpp-krs/chime/chime_env/2019_01_py3/stable_base.sh
  virtualenv --system-site-packages --python=python3 --prompt='(p3_chimeenv)' venv
  source venv/bin/activate
  pip install git+ssh://git@github.com/radiocosmology/caput#egg=caput

full traceback:

 Ignoring pip: markers 'python_version < "3"' don't match your environment
 Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs /soft.computecanada.ca/custom/python/wheelhouse/generic
 Collecting caput from git+ssh://git@github.com/radiocosmology/caput#egg=caput
 Cloning ssh://git@github.com/radiocosmology/caput to /tmp/pip-install-ulbmu86d/caput
 Running command git clone -q ssh://git@github.com/radiocosmology/caput /tmp/pip-install-ulbmu86d/caput
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 ERROR: Exception:
 Traceback (most recent call last):
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 188, in main
 status = self.run(options, args)
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 345, in run
 resolver.resolve(requirement_set)
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
 self._resolve_one(requirement_set, req)
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
 abstract_dist = self._get_abstract_dist_for(req_to_install)
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
 self.require_hashes
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 215, in prepare_linked_requirement
 finder, self.build_isolation,
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_internal/distributions/source.py", line 70, in prepare_distribution_metadata
 reqs = self.req.pep517_backend.get_requires_for_build_wheel()
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
 'config_settings': config_settings
 File "/home/fandino/virtualenvs/p3chimeenv/venv/lib/python3.5/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
 raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable```

@ketiltrout

**Comment by fandinomat** [comment]
Possibly related to this:

https://github.com/pypa/pip/issues/6264

https://github.com/pypa/setuptools/issues/1694

**Comment by jrs65** [comment]
@fandinomat if you want to install on cedar. I would base on top of `2019_09` which is a much more recent and thorough Python 3 install.
